# Generated by Django 5.1.3 on 2024-11-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lableText', models.CharField(max_length=255)),
                ('dropdownRequired', models.BooleanField()),
                ('readMore', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSparepart',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('itemDescription', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(max_length=255)),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.dropdownfield')),
                ('itemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.syncsparepart')),
            ],
        ),
        migrations.CreateModel(
            name='SyncBomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(max_length=25)),
                ('itemDescription', models.CharField(max_length=255)),
                ('quantity', models.SmallIntegerField()),
                ('parentItemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.syncsparepart')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isFavorite', models.BooleanField()),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownfield')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownoption')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(verbose_name=25)),
                ('price', models.IntegerField(max_length=255)),
                ('itemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.syncsparepart')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.user')),
            ],
        ),
    ]
