# Generated by Django 5.1.3 on 2024-12-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_ordernumber_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncbomlist',
            name='itemDescription',
        ),
        migrations.RemoveField(
            model_name='syncsparepart',
            name='price',
        ),
        migrations.AddField(
            model_name='dropdownfield',
            name='parentCategory',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropdownfield',
            name='lableText',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dropdownoption',
            name='optionText',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syncbomlist',
            name='no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_clild_item', to='order.syncsparepart'),
        ),
        migrations.AlterField(
            model_name='syncbomlist',
            name='parentItemNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent_item', to='order.syncsparepart'),
        ),
        migrations.AlterField(
            model_name='syncsparepart',
            name='itemDescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syncsparepart',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceEUR', models.IntegerField()),
                ('priceDKK', models.IntegerField()),
                ('priceUSD', models.IntegerField()),
                ('priceAUD', models.IntegerField()),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.syncsparepart')),
            ],
        ),
        migrations.CreateModel(
            name='UserSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isFavorite', models.BooleanField()),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownfield')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSaveChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownfield')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownoption')),
                ('saveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.usersave')),
            ],
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
