# Generated by Django 5.1.3 on 2024-12-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_dropdownfield_readmore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.syncsparepart')),
                ('orderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
