# Generated by Django 5.1.3 on 2024-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
