# Generated by Django 5.1.3 on 2024-12-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_id_alter_order_ordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavechoise',
            name='saveId',
        ),
        migrations.RemoveField(
            model_name='usersavechoise',
            name='fieldId',
        ),
        migrations.RemoveField(
            model_name='usersavechoise',
            name='optionId',
        ),
        migrations.AlterField(
            model_name='dropdownfield',
            name='parentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.dropdownfield'),
        ),
        migrations.DeleteModel(
            name='UserSave',
        ),
        migrations.DeleteModel(
            name='UserSaveChoise',
        ),
    ]
