# Generated by Django 5.1.3 on 2024-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_usersavechoise_saveid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownfield',
            name='parentImgUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
